PROGRAM_DEBUG_FLAG = -g
PROGRAM_OP_FLAG = -O1
# PROGRAM_SANITIZE_FLAG = -fsanitize=address -fsanitize=leak -fsanitize=undefined -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow

# ASM_DEBUG_FLAG = -g
ASM_OP_FLAG = -O1

PROGRAM_NAME = a

include ../Makefile
